FROM ubuntu:18.04

# non-persistent environment variables
ARG DEBIAN_FRONTEND=noninteractive

# Basic packages
RUN apt-get update && apt-get install -y \
    apt-utils \
    apt-transport-https \
    aptitude \
    software-properties-common \
    locales \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set the locale
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# Install base dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    clang \
    clang-7 \
    clang-8 \
    clang-9 \
    g++-7 \
    g++-8 \
    libc++-dev \
    clang-format \
    cmake \
    pkg-config \
    wget \
    curl \
    git \
    ccache

# Python
RUN apt-get update && apt-get install -y \
    python \
    python3 \
    libpython-all-dev \
    libpython3-all-dev

# Install larger libs
RUN apt-get update && apt-get install -y \
    libboost-all-dev
    
# Install some tools
RUN apt-get update && apt-get install -y \
    emacs \
    vim \
    cmake-curses-gui

# Install additional libs
RUN apt-get update && apt-get install -y \
    libgoogle-glog-dev \
    libtbb-dev \
    libeigen3-dev \
    libceres-dev

