FROM ubuntu:16.04

# non-persistent environment variables
ARG DEBIAN_FRONTEND=noninteractive

# Basic packages
RUN apt-get update && apt-get install -y \
    software-properties-common \
    locales \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set the locale
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# Install base dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    clang \
    clang-4.0 \
    clang-5.0 \
    cmake \
    pkg-config \
    wget \
    python \
    git \
    ccache \
    aptitude

# Install larger libs
RUN apt-get update && apt-get install -y \
    libboost-all-dev

# Install some tools
RUN apt-get update && apt-get install -y \
    emacs \
    vim

# Install additional libs
RUN apt-get update && apt-get install -y \
    libgoogle-glog-dev
